// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POSEIDON.DataAccess.Data;

#nullable disable

namespace POSEIDON.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230815042717_ExtendIdentityUser")]
    partial class ExtendIdentityUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("POSEIDON.Models.Barangay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BarangayCode")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("LocationType")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("PlantId");

                    b.ToTable("Barangays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BarangayCode = "01",
                            Created_At = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(4040),
                            DistrictId = 20,
                            LocationType = "Urban",
                            Name = "Punta-Baja",
                            PlantId = 1,
                            Status = "Active",
                            Updated_At = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(4041)
                        },
                        new
                        {
                            Id = 2,
                            BarangayCode = "02",
                            Created_At = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(4043),
                            DistrictId = 20,
                            LocationType = "Rural",
                            Name = "Bunog",
                            PlantId = 1,
                            Status = "Active",
                            Updated_At = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(4043)
                        },
                        new
                        {
                            Id = 3,
                            BarangayCode = "03",
                            Created_At = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(4045),
                            DistrictId = 20,
                            LocationType = "Rural",
                            Name = "Iraan",
                            PlantId = 1,
                            Status = "Active",
                            Updated_At = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(4046)
                        },
                        new
                        {
                            Id = 4,
                            BarangayCode = "04",
                            Created_At = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(4047),
                            DistrictId = 20,
                            LocationType = "Rural",
                            Name = "Campong-Ulay",
                            PlantId = 1,
                            Status = "Active",
                            Updated_At = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(4048)
                        },
                        new
                        {
                            Id = 5,
                            BarangayCode = "05",
                            Created_At = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(4049),
                            DistrictId = 20,
                            LocationType = "Rural",
                            Name = "Ransang",
                            PlantId = 1,
                            Status = "Inactive",
                            Updated_At = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(4050)
                        },
                        new
                        {
                            Id = 6,
                            BarangayCode = "06",
                            Created_At = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(4052),
                            DistrictId = 20,
                            LocationType = "Rural",
                            Name = "Candawaga",
                            PlantId = 1,
                            Status = "Inactive",
                            Updated_At = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(4052)
                        },
                        new
                        {
                            Id = 7,
                            BarangayCode = "07",
                            Created_At = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(4054),
                            DistrictId = 20,
                            LocationType = "Rural",
                            Name = "Culasian",
                            PlantId = 1,
                            Status = "Inactive",
                            Updated_At = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(4054)
                        },
                        new
                        {
                            Id = 8,
                            BarangayCode = "08",
                            Created_At = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(4055),
                            DistrictId = 20,
                            LocationType = "Rural",
                            Name = "Panalingaan",
                            PlantId = 1,
                            Status = "Inactive",
                            Updated_At = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(4056)
                        },
                        new
                        {
                            Id = 9,
                            BarangayCode = "09",
                            Created_At = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(4092),
                            DistrictId = 20,
                            LocationType = "Rural",
                            Name = "Taburi",
                            PlantId = 1,
                            Status = "Inactive",
                            Updated_At = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(4092)
                        },
                        new
                        {
                            Id = 10,
                            BarangayCode = "10",
                            Created_At = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(4094),
                            DistrictId = 20,
                            LocationType = "Rural",
                            Name = "Latud",
                            PlantId = 1,
                            Status = "Inactive",
                            Updated_At = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(4095)
                        },
                        new
                        {
                            Id = 11,
                            BarangayCode = "11",
                            Created_At = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(4096),
                            DistrictId = 20,
                            LocationType = "Rural",
                            Name = "Canipaan",
                            PlantId = 1,
                            Status = "Inactive",
                            Updated_At = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(4097)
                        });
                });

            modelBuilder.Entity("POSEIDON.Models.Classification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("isBulk")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("Classifications");
                });

            modelBuilder.Entity("POSEIDON.Models.Cluster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BarangayId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BarangayId");

                    b.ToTable("Clusters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BarangayId = 1,
                            Code = "001",
                            Created_At = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(4123),
                            Name = "Malapandeg",
                            Status = "Active",
                            Updated_At = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(4124)
                        },
                        new
                        {
                            Id = 2,
                            BarangayId = 1,
                            Code = "002",
                            Created_At = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(4126),
                            Name = "Katutubo",
                            Status = "Active",
                            Updated_At = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(4126)
                        });
                });

            modelBuilder.Entity("POSEIDON.Models.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Districts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Aborlan",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3965),
                            updated_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3966)
                        },
                        new
                        {
                            Id = 2,
                            Name = "Agutaya",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3968),
                            updated_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3969)
                        },
                        new
                        {
                            Id = 3,
                            Name = "Araceli",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3970),
                            updated_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3971)
                        },
                        new
                        {
                            Id = 4,
                            Name = "Balabac",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3972),
                            updated_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3972)
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bataraza",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3973),
                            updated_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3975)
                        },
                        new
                        {
                            Id = 6,
                            Name = "Brooke's Point",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3976),
                            updated_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3976)
                        },
                        new
                        {
                            Id = 7,
                            Name = "Busuanga",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3977),
                            updated_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3978)
                        },
                        new
                        {
                            Id = 8,
                            Name = "Cagayancillo",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3979),
                            updated_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3979)
                        },
                        new
                        {
                            Id = 9,
                            Name = "Coron",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3980),
                            updated_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3981)
                        },
                        new
                        {
                            Id = 10,
                            Name = "Culion",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3982),
                            updated_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3982)
                        },
                        new
                        {
                            Id = 11,
                            Name = "Cuyo",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3983),
                            updated_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3984)
                        },
                        new
                        {
                            Id = 12,
                            Name = "Dumaran",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3985),
                            updated_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3985)
                        },
                        new
                        {
                            Id = 13,
                            Name = "El Nido",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3986),
                            updated_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3987)
                        },
                        new
                        {
                            Id = 14,
                            Name = "Kalayaan",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3988),
                            updated_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3988)
                        },
                        new
                        {
                            Id = 15,
                            Name = "Linapacan",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3989),
                            updated_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3990)
                        },
                        new
                        {
                            Id = 16,
                            Name = "Magsaysay",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3991),
                            updated_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3991)
                        },
                        new
                        {
                            Id = 17,
                            Name = "Narra",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3992),
                            updated_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3993)
                        },
                        new
                        {
                            Id = 18,
                            Name = "Puerto Princesa",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3994),
                            updated_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3994)
                        },
                        new
                        {
                            Id = 19,
                            Name = "Quezon",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3995),
                            updated_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3996)
                        },
                        new
                        {
                            Id = 20,
                            Name = "Rizal",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3997),
                            updated_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3997)
                        },
                        new
                        {
                            Id = 21,
                            Name = "Roxas",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3998),
                            updated_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3999)
                        },
                        new
                        {
                            Id = 22,
                            Name = "San Vicente",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(4000),
                            updated_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(4000)
                        },
                        new
                        {
                            Id = 23,
                            Name = "Sofronio Española",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(4001),
                            updated_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(4002)
                        },
                        new
                        {
                            Id = 24,
                            Name = "Taytay",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(4003),
                            updated_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(4003)
                        });
                });

            modelBuilder.Entity("POSEIDON.Models.MeterReader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("MeterReaders");
                });

            modelBuilder.Entity("POSEIDON.Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_At = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(4149),
                            DistrictId = 1,
                            Name = "Calupisan River Water System",
                            Status = "Active",
                            Updated_At = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(4149)
                        },
                        new
                        {
                            Id = 2,
                            Created_At = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(4151),
                            DistrictId = 1,
                            Name = "Magtayob River Water System",
                            Status = "Active",
                            Updated_At = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(4151)
                        });
                });

            modelBuilder.Entity("POSEIDON.Models.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Palawan",
                            created_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3735),
                            updated_at = new DateTime(2023, 8, 15, 12, 27, 17, 44, DateTimeKind.Local).AddTicks(3747)
                        });
                });

            modelBuilder.Entity("POSEIDON.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("District")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("POSEIDON.Models.Barangay", b =>
                {
                    b.HasOne("POSEIDON.Models.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("POSEIDON.Models.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("POSEIDON.Models.Classification", b =>
                {
                    b.HasOne("POSEIDON.Models.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("POSEIDON.Models.Cluster", b =>
                {
                    b.HasOne("POSEIDON.Models.Barangay", "Barangay")
                        .WithMany()
                        .HasForeignKey("BarangayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barangay");
                });

            modelBuilder.Entity("POSEIDON.Models.District", b =>
                {
                    b.HasOne("POSEIDON.Models.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("POSEIDON.Models.MeterReader", b =>
                {
                    b.HasOne("POSEIDON.Models.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("POSEIDON.Models.Plant", b =>
                {
                    b.HasOne("POSEIDON.Models.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });
#pragma warning restore 612, 618
        }
    }
}
