// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POSEIDON.DataAccess.Data;

#nullable disable

namespace POSEIDON.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("POSEIDON.Models.Barangay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BarangayCode")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("LocationType")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("PlantId");

                    b.ToTable("Barangays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BarangayCode = "01",
                            Created_At = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9762),
                            DistrictId = 20,
                            LocationType = "Urban",
                            Name = "Punta-Baja",
                            PlantId = 1,
                            Status = "Active",
                            Updated_At = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9763)
                        },
                        new
                        {
                            Id = 2,
                            BarangayCode = "02",
                            Created_At = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9765),
                            DistrictId = 20,
                            LocationType = "Rural",
                            Name = "Bunog",
                            PlantId = 1,
                            Status = "Active",
                            Updated_At = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9765)
                        },
                        new
                        {
                            Id = 3,
                            BarangayCode = "03",
                            Created_At = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9767),
                            DistrictId = 20,
                            LocationType = "Rural",
                            Name = "Iraan",
                            PlantId = 1,
                            Status = "Active",
                            Updated_At = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9767)
                        },
                        new
                        {
                            Id = 4,
                            BarangayCode = "04",
                            Created_At = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9769),
                            DistrictId = 20,
                            LocationType = "Rural",
                            Name = "Campong-Ulay",
                            PlantId = 1,
                            Status = "Active",
                            Updated_At = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9769)
                        },
                        new
                        {
                            Id = 5,
                            BarangayCode = "05",
                            Created_At = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9771),
                            DistrictId = 20,
                            LocationType = "Rural",
                            Name = "Ransang",
                            PlantId = 1,
                            Status = "Inactive",
                            Updated_At = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9771)
                        },
                        new
                        {
                            Id = 6,
                            BarangayCode = "06",
                            Created_At = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9773),
                            DistrictId = 20,
                            LocationType = "Rural",
                            Name = "Candawaga",
                            PlantId = 1,
                            Status = "Inactive",
                            Updated_At = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9773)
                        },
                        new
                        {
                            Id = 7,
                            BarangayCode = "07",
                            Created_At = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9775),
                            DistrictId = 20,
                            LocationType = "Rural",
                            Name = "Culasian",
                            PlantId = 1,
                            Status = "Inactive",
                            Updated_At = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9775)
                        },
                        new
                        {
                            Id = 8,
                            BarangayCode = "08",
                            Created_At = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9776),
                            DistrictId = 20,
                            LocationType = "Rural",
                            Name = "Panalingaan",
                            PlantId = 1,
                            Status = "Inactive",
                            Updated_At = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9777)
                        },
                        new
                        {
                            Id = 9,
                            BarangayCode = "09",
                            Created_At = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9778),
                            DistrictId = 20,
                            LocationType = "Rural",
                            Name = "Taburi",
                            PlantId = 1,
                            Status = "Inactive",
                            Updated_At = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9779)
                        },
                        new
                        {
                            Id = 10,
                            BarangayCode = "10",
                            Created_At = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9780),
                            DistrictId = 20,
                            LocationType = "Rural",
                            Name = "Latud",
                            PlantId = 1,
                            Status = "Inactive",
                            Updated_At = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9781)
                        },
                        new
                        {
                            Id = 11,
                            BarangayCode = "11",
                            Created_At = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9782),
                            DistrictId = 20,
                            LocationType = "Rural",
                            Name = "Canipaan",
                            PlantId = 1,
                            Status = "Inactive",
                            Updated_At = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9783)
                        });
                });

            modelBuilder.Entity("POSEIDON.Models.Classification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("isBulk")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("Classifications");
                });

            modelBuilder.Entity("POSEIDON.Models.Cluster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BarangayId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BarangayId");

                    b.ToTable("Clusters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BarangayId = 1,
                            Code = "001",
                            Created_At = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9807),
                            Name = "Malapandeg",
                            Status = "Active",
                            Updated_At = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9807)
                        },
                        new
                        {
                            Id = 2,
                            BarangayId = 1,
                            Code = "002",
                            Created_At = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9810),
                            Name = "Katutubo",
                            Status = "Active",
                            Updated_At = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9810)
                        });
                });

            modelBuilder.Entity("POSEIDON.Models.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Districts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Aborlan",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9659),
                            updated_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9660)
                        },
                        new
                        {
                            Id = 2,
                            Name = "Agutaya",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9662),
                            updated_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9662)
                        },
                        new
                        {
                            Id = 3,
                            Name = "Araceli",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9663),
                            updated_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9664)
                        },
                        new
                        {
                            Id = 4,
                            Name = "Balabac",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9665),
                            updated_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9665)
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bataraza",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9666),
                            updated_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9667)
                        },
                        new
                        {
                            Id = 6,
                            Name = "Brooke's Point",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9668),
                            updated_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9668)
                        },
                        new
                        {
                            Id = 7,
                            Name = "Busuanga",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9669),
                            updated_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9671)
                        },
                        new
                        {
                            Id = 8,
                            Name = "Cagayancillo",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9672),
                            updated_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9672)
                        },
                        new
                        {
                            Id = 9,
                            Name = "Coron",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9673),
                            updated_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9674)
                        },
                        new
                        {
                            Id = 10,
                            Name = "Culion",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9675),
                            updated_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9675)
                        },
                        new
                        {
                            Id = 11,
                            Name = "Cuyo",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9676),
                            updated_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9677)
                        },
                        new
                        {
                            Id = 12,
                            Name = "Dumaran",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9678),
                            updated_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9678)
                        },
                        new
                        {
                            Id = 13,
                            Name = "El Nido",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9679),
                            updated_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9680)
                        },
                        new
                        {
                            Id = 14,
                            Name = "Kalayaan",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9681),
                            updated_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9681)
                        },
                        new
                        {
                            Id = 15,
                            Name = "Linapacan",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9682),
                            updated_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9683)
                        },
                        new
                        {
                            Id = 16,
                            Name = "Magsaysay",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9684),
                            updated_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9684)
                        },
                        new
                        {
                            Id = 17,
                            Name = "Narra",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9685),
                            updated_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9686)
                        },
                        new
                        {
                            Id = 18,
                            Name = "Puerto Princesa",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9686),
                            updated_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9687)
                        },
                        new
                        {
                            Id = 19,
                            Name = "Quezon",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9688),
                            updated_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9688)
                        },
                        new
                        {
                            Id = 20,
                            Name = "Rizal",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9689),
                            updated_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9690)
                        },
                        new
                        {
                            Id = 21,
                            Name = "Roxas",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9691),
                            updated_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9691)
                        },
                        new
                        {
                            Id = 22,
                            Name = "San Vicente",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9692),
                            updated_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9693)
                        },
                        new
                        {
                            Id = 23,
                            Name = "Sofronio Española",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9694),
                            updated_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9694)
                        },
                        new
                        {
                            Id = 24,
                            Name = "Taytay",
                            ProvinceId = 1,
                            created_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9695),
                            updated_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9696)
                        });
                });

            modelBuilder.Entity("POSEIDON.Models.MeterReader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("MeterReaders");
                });

            modelBuilder.Entity("POSEIDON.Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_At = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9831),
                            DistrictId = 1,
                            Name = "Calupisan River Water System",
                            Status = "Active",
                            Updated_At = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9832)
                        },
                        new
                        {
                            Id = 2,
                            Created_At = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9833),
                            DistrictId = 1,
                            Name = "Magtayob River Water System",
                            Status = "Active",
                            Updated_At = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9834)
                        });
                });

            modelBuilder.Entity("POSEIDON.Models.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Palawan",
                            created_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9479),
                            updated_at = new DateTime(2023, 8, 15, 3, 4, 47, 799, DateTimeKind.Local).AddTicks(9491)
                        });
                });

            modelBuilder.Entity("POSEIDON.Models.Barangay", b =>
                {
                    b.HasOne("POSEIDON.Models.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("POSEIDON.Models.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("POSEIDON.Models.Classification", b =>
                {
                    b.HasOne("POSEIDON.Models.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("POSEIDON.Models.Cluster", b =>
                {
                    b.HasOne("POSEIDON.Models.Barangay", "Barangay")
                        .WithMany()
                        .HasForeignKey("BarangayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barangay");
                });

            modelBuilder.Entity("POSEIDON.Models.District", b =>
                {
                    b.HasOne("POSEIDON.Models.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("POSEIDON.Models.MeterReader", b =>
                {
                    b.HasOne("POSEIDON.Models.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("POSEIDON.Models.Plant", b =>
                {
                    b.HasOne("POSEIDON.Models.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });
#pragma warning restore 612, 618
        }
    }
}
